---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(scales)
library(ggthemes)
theme_set(theme_light())
```

```{r}
dataset <- read_csv("./sliced-s01e05/train.csv") %>% 
  mutate(price = log(price + 1))

holdout <- read_csv("./sliced-s01e05/test.csv")

set.seed(2021)

spl <-  initial_split(dataset, 0.75)

train <- training(spl)

test <- testing(spl)

```

```{r}
glimpse(train)

train %>% 
  ggplot(aes(x = price)) +
  geom_histogram()

sum_prices <-  function(tbl) {
  tbl %>%  
    summarise(avg_price = exp(mean(price)) - 1,
              median_price = exp(median(price)) -1,
              n = n()) %>% 
    arrange(desc(n))
}

train %>% 
  group_by(neighbourhood_group) %>% 
  sum_prices() %>% 
  ggplot(aes())

train %>%  
  mutate(neighbourhood_group = fct_reorder(neighbourhood_group, price)) %>% 
  ggplot(aes(x = exp(price), y = neighbourhood_group)) + 
  geom_boxplot() +
  scale_x_log10()

train %>%  
  mutate(neighbourhood = fct_lump(neighbourhood, 40),
         neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  ggplot(aes(x = exp(price), y = neighbourhood)) + 
  geom_boxplot() +
  scale_x_log10()
```

```{r}
train %>%  
  mutate(room_type = fct_reorder(room_type, price)) %>% 
  ggplot(aes(x = exp(price), y = room_type)) + 
  geom_boxplot() +
  scale_x_log10()
```
 
```{r}
train %>% 
  group_by(latitude = round(latitude, 2),
           longitude = round(longitude, 2)) %>%  
  ggplot(aes(x = longitude, y = latitude, colour = price)) + 
  geom_point() + 
  scale_colour_gradient2(low = "blue", high = "red", midpoint = 2, trans = "log10")
  
```
 

