---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
library(tidymodels)
library(irlba)
library(tidylo)
library(textrecipes)

user_reviews <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/user_reviews.tsv')
```

```{r}
user_reviews %>%  
  count(grade) %>% 
  ggplot(aes(x = grade, y = n)) +
  geom_col()
```

```{r}
sparse_df <- user_reviews %>% 
  select(grade, text) %>% 
  unnest_tokens("word", "text") %>% 
  count(grade, word) %>% 
  anti_join(stop_words) %>% 
  filter(n >= 5) %>% 
  group_by(grade) %>% 
  top_n(n, n = 25) %>% 
  cast_sparse(row = grade, column = word, value = n)

pca_text <-  prcomp_irlba(sparse_df, n = 4, scale. = TRUE)

glimpse(pca_text)

pca_text$center %>% 
  tidy() %>% 
  select(names) %>% 
  cbind(pca_text$rotation) %>% 
  ggplot(aes(x = PC1, y = PC2, label = names)) + 
  geom_point() +
  geom_text()
```


```{r}
user_reviews %>% 
  unnest_tokens("word", "text") %>% 
  count(grade, word) %>% 
  anti_join(stop_words) %>% 
  filter(n >= 5) %>% 
  bind_tf_idf(word, grade, n) %>% 
  group_by(grade) %>% 
  top_n(tf_idf, n = 5) %>% 
  ungroup() %>% 
  mutate(grade = as.factor(grade)) %>% 
  ggplot(aes(x = reorder_within(word, tf_idf, grade), y = tf_idf, fill = grade)) +
  geom_col() +
  scale_x_reordered() + 
  coord_flip() +
  facet_wrap(~ grade, scales = "free") + 
  theme(legend.position = "none")
```


```{r}
user_reviews %>% 
  unnest_tokens("word", "text") %>% 
  count(grade, word) %>% 
  anti_join(stop_words) %>% 
  filter(n >= 5) %>% 
  bind_log_odds(grade, word, n, unweighted = TRUE) %>% 
  group_by(grade) %>% 
  top_n(log_odds_weighted, n = 8) %>% 
  ungroup() %>% 
  mutate(grade = as.factor(grade)) %>% 
  ggplot(aes(x = reorder_within(word, log_odds_weighted, grade), y = log_odds_weighted, fill = grade)) +
  geom_col() +
  scale_x_reordered() + 
  coord_flip() +
  facet_wrap(~ grade, scales = "free") + 
  theme(legend.position = "none")

```

```{r}
set.seed(42)

tidy_data <- user_reviews %>% select(-user_name)

tidy_split <- initial_split(tidy_data, prop = 0.8)

tidy_train <- training(tidy_split)

tidy_test <- testing(tidy_split)
```

```{r}
text_recipe <- recipe(grade ~ text, data = tidy_train) %>% 
  step_tokenize(text) %>% 
  step_stopwords(text) %>% 
  step_tokenfilter(text, max_tokens = 500) %>% 
  step_tf(text)

text_prep <- text_recipe %>% prep()

cross_validation <-  vfold_cv(tidy_train, v = 10, repeats = 10)
```


