---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(broom)
library(tidymodels)
library(progress)
```

```{r}
iris %>% 
  mutate(sqrt_sepal_length = sqrt(Sepal.Length),
         map_sqrt = map_dbl(Sepal.Length, sqrt))
```

```{r}
iris %>% 
  mutate(map_log = map_dbl(Sepal.Length, log, base = 3))

# don't actually do it this way 
iris %>% 
  mutate(base = 3) %>% 
  mutate(map_sqrt = map2_dbl(Sepal.Length, base, log))
```

```{r}
iris %>% 
  nest(-Species) %>% 
  mutate(model = map(data, ~lm(Sepal.Length ~ Sepal.Width + Petal.Length + Petal.Width, data = .x)), 
         tidy_model = map(model, tidy)) %>% 
  select(Species, tidy_model) %>% 
  unnest() %>% 
  ggplot(aes(x = term, y = estimate, colour = Species)) + 
  geom_point()
  
```

```{r}
set.seed(54)

model_data <- iris %>% 
  nest(-Species) %>% 
  mutate(data_splits = map(data, initial_split, prop = 0.8), 
         train_data = map(data_splits, training), 
         test_data = map(data_splits, testing))

rf_model <- rand_forest(trees = tune()) %>% 
  set_mode("regression") %>% 
  set_engine("randomForest")

rf_grid <- grid_regular(parameters(rf_model))
  

```


```{r}
# creating k folfd and recipe
model_data <- model_data %>% 
  mutate(recipe = map(train_data, .f = function(x){
    recipe(Sepal.Length ~ ., data = x)
  }),
  kfolds_data = map(train_data, vfold_cv))
```

```{r}
train_models <- function(recipe, kfolds_data){
  tune_grid(
    rf_model,
    recipe, 
    grid = rf_grid, 
    resamples = kfolds_data
  )
}
```


```{r}
model_data <- model_data %>%  
  mutate(tune_results = map2(recipe, kfolds_data, train_models))
```

```{r}
model_data <- model_data %>% 
  mutate(parameters = map(tune_results, ~show_best(.x, "rmse", n = 1)),
         final_model = map2(parameters, recipe, .f = function(x, y){
           workflow() %>% 
             add_model(rf_model) %>% 
             add_recipe(y) %>% 
             finalize_workflow(x)
         }),
         eval = map2(final_model, data_splits, last_fit))
```

```{r}
model_data %>% 
  select(Species, eval) %>% 
  mutate(metrics = map(eval, collect_metrics)) %>% 
  select(Species, metrics) %>% 
  unnest()
```

```{r}
iris %>% 
  nest(-Species) %>% 
  mutate(chart = map(data, .f = function(x){
    ggplot(data = x, aes(x = Sepal.Length, y = Sepal.Width)) + 
      geom_point() + 
      geom_smooth(method = "lm")
  })) %>%  
  pull(chart)
```


```{r}

```

