---
title: "Untitled"
output: html_document
date: '2022-04-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(tidymodels)
library(textrecipes)
library(lubridate)
theme_set(theme_light())
tuesdata <- tidytuesdayR::tt_load('2021-09-14')
```

```{r}
billboard <- tuesdata$billboard %>% 
  mutate(week = mdy(week_id)) %>% 
  select(-week_id)

```

```{r}
top1 <- billboard %>% 
  filter(week_position == 1) %>% 
  count(song_id, song, performer, sort = TRUE)

billboard %>%
  semi_join(head(top1, 9), by = "song_id") %>% 
  ggplot(aes(x = week, y = week_position, group = instance)) + 
  geom_line() + 
  facet_wrap(~ song, scales = "free_x") + 
  scale_y_reverse() + 
  labs(x = "Date", y = "Billboard position", 
       title = "What are the trajectories of #1 hits?")
```

```{r}
summarise_songs <- function(tbl) {
  tbl %>% 
    summarise(total_weeks_100 = n(),
            total_weeks_1 = sum(week_position == 1),
            n_songs_100 = n_distinct(song),
            n_songs_1 = n_distinct(song[week_position == 1]), 
            .groups = "drop") %>% 
    arrange(desc(n_songs_1))
}
```


```{r}
performer <- billboard %>% 
  group_by(performer) %>% 
  summarise_songs()

performer %>% 
  arrange(desc(n_songs_1)) %>% 
  head(30) %>% 
  mutate(performer = fct_reorder(performer, n_songs_1)) %>% 
  ggplot(aes(x = n_songs_1, y = performer)) +
  geom_col() +
  labs(x = "Number of songs at #1")

performer %>% 
  arrange(desc(n_songs_100)) %>% 
  head(100) %>% 
  ggplot(aes(x = n_songs_100, y = n_songs_1)) + 
  geom_point() +
  geom_text(aes(label = performer), check_overlap = TRUE, vjust = 1, hjust = 1) +
  expand_limits(x = -10)
```

```{r}
performer_decade <- billboard %>% 
  group_by(performer,
           decade = 10 * year(week) %/% 10) %>% 
  summarise_songs()

performer_decade %>% 
  group_by(decade) %>% 
  slice_max(total_weeks_1, n = 1)

billboard %>% 
  mutate(performer_lumped = fct_lump(performer, 16)) %>% 
  count(performer_lumped, 
        year = 5 * year(week) %/% 5) %>% 
  filter(performer_lumped != "Other") %>% 
  ggplot(aes(x = year, y = n, fill = performer_lumped)) + 
  geom_area() + 
  facet_wrap(~ performer_lumped, scales = "free_y") + 
  scale_fill_discrete(guide = "none") + 
  labs(x = "Year", 
       y = "Average weeks on Billboard 100")
```

# machine learning


```{r}
by_song <- billboard %>% 
  group_by(song_id) %>% 
  summarise(peak = min(week_position),
            first_week = min(week), 
            n_weeks = n(),
            log_n_weeks = log2(n_weeks))

songs_joined <- by_song %>% 
  inner_join(tuesdata$audio_features, by = "song_id") %>% 
  filter(!is.na(spotify_track_id))


```


```{r}
set.seed(2021)

spl <- initial_split(songs_joined)
train <- training(spl)
test <- testing(spl)
folds <- vfold_cv(train, 3)
```

### fit a boosted tree

```{r}
xg_wf <- recipe(log_n_weeks ~ danceability + energy + key + loudness + mode + speechiness + acousticness + 
         instrumentalness + liveness + valence + tempo + time_signature + spotify_genre + first_week, data = train) %>% 
  step_mutate(month = month(first_week),
              spotify_genre = str_remove_all(spotify_genre, "\\['|'\\]")) %>% 
  step_rm(first_week) %>% 
  step_tokenize(spotify_genre, token = "regex", options = list(pattern = "', '")) %>% 
  step_tokenfilter(spotify_genre, max_tokens = tune()) %>% 
  step_tf(spotify_genre) %>% 
  workflow(boost_tree("regression",
                      mtry = tune(),
                      trees = tune(),
                      learn_rate = .02))

tune <- xg_wf %>% 
  tune_grid(folds, 
            metrics = metric_set(rmse),
            grid = crossing(mtry = c(3, 5),
                            max_tokens = c(3, 10, 30),
                            trees = seq(25, 400, 25)))

dtune <- xg_wf %>%
  tune_grid(folds,
            metrics = metric_set(rmse),
            grid = crossing(mtry = c(3, 5),
                            trees = seq(25, 500, 25)))

autoplot(tune)
  
```


