---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(skimr)
library(scales)
library(themis)
members <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-22/members.csv")


```

```{r}
members %>% 
  count(peak_id, sort = TRUE)

skim(members)
```

```{r}
members %>% 
  group_by(age = 10 * (age %/% 10)) %>% 
  summarise(died = mean(died),
            success = mean(success)) %>% 
  pivot_longer(cols = c(died, success), names_to = "outcome", values_to = "percent") %>% 
  ggplot(aes(x = age, y = percent, colour = outcome)) +
  geom_line(alpha = 0.7, size = 1) +
  scale_y_continuous(labels = percent_format(accuracy = 1))
  
```

```{r}
members %>% 
  count(success, died) %>% 
  group_by(success) %>%
  mutate(peercent = n / sum(n))
  
```

```{r}
members %>% 
  filter(!is.na(peak_name)) %>% 
  mutate(peak_name = fct_lump(peak_name, prop = 0.05)) %>% 
  count(peak_name, died) %>% 
  group_by(peak_name) %>% 
  mutate(percent = n / sum(n))

members %>% 
  filter(!is.na(peak_name)) %>% 
  mutate(peak_name = fct_lump(peak_name, 10)) %>% 
  group_by(peak_name) %>% 
  summarise(died = mean(died),
            success = mean(success)) %>% 
  mutate(peak_name = fct_reorder(peak_name, died)) %>% 
  pivot_longer(cols = c(died, success), names_to = "outcome", values_to = "percent") %>% 
  ggplot(aes(x = percent, y = peak_name, fill = outcome)) +
  geom_col() +
  scale_x_continuous(labels = percent_format(accuracy = 1)) +
  facet_wrap(~outcome, scales = "free_x")
  count(peak_name, sort = TRUE)
```


```{r}
members %>% 
  filter(season != "Unknown") %>% 
  count(season, died) %>% 
  group_by(season) %>% 
  mutate(percent = n / sum(n), 
         died = case_when(died ~ "Died",
                          TRUE ~ "Did not die")) %>% 
  ggplot(aes(season, percent, fill = season)) +
  geom_col(show.legend = FALSE, position = "dodge") +
  facet_wrap(~ died, scales = "free") +
  scale_y_continuous(labels = percent_format())
```

### what do we want in the dataset that we want to use?

```{r}
members_df <- members %>% 
  filter(season != "Unknown") %>% 
  select(peak_id, year, season, sex, age, citizenship, hired, success, died) %>% 
  filter(!is.na(sex), !is.na(citizenship)) %>% 
  mutate(died = case_when(died ~ "died",
                          TRUE ~ "survived")) %>% 
  mutate_if(is.character, factor) %>% 
  mutate_if(is.logical, as.integer)
```
### splitting data

```{r}
set.seed(123)

members_split <- initial_split(members_df, strata = died)

train <- training(members_split)

test <- testing(members_split)

# setting cv resamples 

set.seed(345)

folds <- vfold_cv(train)
```

### feature engineering or data preprocessing

```{r}
# the goal with imputation is not to add data, it's just to not throw observations away
# step_smote upsamples using nearest neigbours 

members_rec <- recipe(died ~ ., data = train) %>% 
  step_impute_median(age) %>% 
  step_other(peak_id, citizenship) %>% 
  step_dummy(all_nominal(), -died) %>% 
  step_smote(died)

```


```{r}
glm_spec <- logistic_reg() %>% 
  set_engine("glm")

rf_spec <- rand_forest(trees = 1000) %>% 
  set_engine("ranger") %>% 
  set_mode("classification")
```

```{r}
members_wf <- workflow() %>% 
  add_recipe(members_rec)
```

```{r}
doParallel::registerDoParallel()

# if you don't set any metric, it would compute ROC, AUC and accuracy
glm_rs <- members_wf %>% 
  add_model(glm_spec) %>% 
  fit_resamples(
    resamples = folds, 
    metrics = metric_set(roc_auc, accuracy, sensitivity, specificity),
    control = control_resamples(save_pred = TRUE)
  )

rf_rs <- members_wf %>% 
  add_model(rf_spec) %>% 
  fit_resamples(
    resamples = folds, 
    metrics = metric_set(roc_auc, accuracy, sensitivity, specificity),
    control = control_resamples(save_pred = TRUE)
  )
```

### evaluate models

```{r}
collect_metrics(glm_rs)
collect_metrics(rf_rs)

glm_rs %>% 
  conf_mat_resampled()

rf_rs %>% 
  conf_mat_resampled()
```

```{r}
glm_rs %>% 
  collect_predictions() %>% 
  group_by(id) %>% 
  roc_curve(died, .pred_died) %>% 
  autoplot()
```

```{r}
rf_rs %>% 
  collect_predictions() %>% 
  group_by(id) %>% 
  roc_curve(died, .pred_died) %>% 
  autoplot()
```

```{r}
members_final <- members_wf %>% 
  add_model(glm_spec) %>% 
  last_fit(members_split)

collect_metrics(members_final)

collect_predictions(members_final) %>% 
  conf_mat(died, .pred_class)

members_final %>% 
  pull(.workflow) %>% 
  pluck(1) %>% 
  tidy(exponentiate = TRUE) %>% 
  arrange(estimate) %>% 
  pander::pander()
```

```{r}
members_final %>% 
  pull(.workflow) %>% 
  pluck(1) %>% 
  tidy() %>% 
  filter(term != "(Intercept)") %>%
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(x = estimate, y = term)) + 
  geom_vline(xintercept = 0, colour = "gray50", lty = 2) +
  geom_errorbar(aes(xmin = estimate - std.error,
                 xmax = estimate + std.error),
             width = 0.2) +
  geom_point()
```

