---
title: "Untitled"
author: "Sean Ng"
date: "12/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(lubridate)
library(stringr)
library(ggthemes)
library(fuzzyjoin)
library(countrycode)
library(WDI)
library(widyr)
library(tidytext)

theme_set(theme_light())
tt <- tt_load("2021-03-23")

summarise_votes <- function(tbl, min_votes = 10){
  tbl %>% 
  summarise(n_votes = n(),
            n_yes = sum(vote == "yes"), 
            pc_yes = n_yes / n_votes, 
            .groups = "drop") %>% 
  filter(n_votes >= min_votes) %>% 
  arrange(desc(pc_yes))
}

plot_by <- function(tbl, category){
  tbl %>% 
    filter(!is.na({{ category }})) %>% 
    mutate(category = fct_reorder({{ category }}, pc_yes)) %>% 
    ggplot(aes(year, pc_yes)) +
    geom_line(aes(colour = category)) +
    scale_y_continuous(labels = percent) +
    scale_colour_discrete(guide = guide_legend(reverse = TRUE)) +
    expand_limits(y = 0) +
    labs(y = "% 'yes' votes", 
         x = "Year")
}
```

```{r}
unvotes <- tt$unvotes %>% 
  mutate(vote_number = match(vote, c("no", "abstain", "yes")) -2) %>% 
  left_join(tt$roll_calls %>% 
              select(rcid, date, amend, issue = short), by = "rcid")

glimpse(unvotes)
```

```{r}
by_country <- unvotes %>% 
  group_by(country, country_code) %>% 
  summarise(n_votes = n(),
            n_yes = sum(vote == "yes"), 
            pc_yes = n_yes / n_votes) %>% 
  filter(n_votes >= 100) %>% 
  arrange(desc(pc_yes))
  
```


```{r}
by_country %>% 
  slice(c(1:10, (n()-10):n())) %>% # top 10 and bottom 10 - useful for distributions
  mutate(country = fct_reorder(country, pc_yes)) %>% 
  ggplot(aes(x = pc_yes, y = country)) +
  geom_point(aes(size = n_votes)) +
  scale_x_continuous(labels = percent) +
  labs(x = "% of yes votes in UN", 
       title = "Countries voted 'yes' the least")
```

```{r}
unvotes %>% 
  filter(str_detect(issue, "REFU")) %>% 
  filter(str_detect(issue, "PAL")) %>% 
  group_by(country) %>% 
  summarise_votes() %>% 
  slice(c(1:20, (n()-20):n())) %>% # top 10 and bottom 10 - useful for distributions
  mutate(country = fct_reorder(country, pc_yes)) %>% 
  ggplot(aes(x = pc_yes, y = country)) +
  geom_point(aes(size = n_votes)) +
  scale_x_continuous(labels = percent) +
  scale_size_continuous(range = c(0.3, 3)) +
  labs(x = "% of yes votes in UN", 
       title = "Countries voted 'yes' the least on Palestinian Refugees")

```
```{r}
by_year <- unvotes %>% 
  group_by(year = year(date)) %>% 
  summarise_votes()

by_country_year <- unvotes %>% 
  bind_rows(unvotes %>% mutate(country = "Overall")) %>%
  group_by(year = year(date), country, country_code) %>% 
  summarise_votes()

unvotes %>% 
  group_by(continent = countrycode(country_code, "iso2c", "continent"), 
           year = year(date)) %>% # you can mutate in a group_by
  summarise_votes() %>%
  filter(!is.na(continent)) %>% 
  plot_by(continent)

unvotes %>% 
  group_by(continent = countrycode(country_code, "iso2c", "continent"), 
           year = year(date)) %>% # you can mutate in a group_by
  summarise_votes() %>%
  filter(!is.na(continent)) %>% 
  mutate(continent = fct_reorder(continent, pc_yes)) %>% 
  ggplot(aes(x = year, y = pc_yes, colour = continent)) +
  geom_line() +
  expand_limits(y = 0) +
  scale_y_continuous(labels = percent) +
  scale_colour_discrete(guide = guide_legend(reverse = TRUE)) +
  labs(y = "% 'yes' votes")

```



```{r}
gdp <- WDI(indicator = c(gdp_per_capita = "NY.GDP.PCAP.PP.KD",
                         pop = "SP.POP.TOTL"),
           start = 2005, end = 2005, extra = TRUE) %>% 
  as_tibble() %>% 
  select(country_code = iso2c, income, gdp_per_capita, pop) %>% 
  filter(!is.na(income)) %>% 
  mutate(income = fct_relevel(income, "Low income", "Lower middle income", "Upper middle income", "High income"))

```

```{r}
unvotes %>% 
  inner_join(gdp, by = "country_code") %>% 
  group_by(income, year = year(date)) %>% 
  summarise_votes() %>% 
  plot_by(income)
```


```{r}
by_year %>% 
  ggplot(aes(x = year, y = pc_yes)) +
  geom_line() +
  expand_limits(y = 0)
```

```{r}
by_country_year %>% 
  filter(country %in% c("United States", "Canada", "Mali", "Singapore", "Ghana", "Italy", 
                        "Spain", "Germany", "Israel")) %>% 
  mutate(country = fct_reorder(country, pc_yes)) %>% 
  ggplot(aes(x = year, y = pc_yes)) +
  geom_line(data = by_year, size = 1.5) + # adding in the average for all countries
  geom_line(aes(colour = country)) +
  expand_limits(y = 0) +
  scale_y_continuous(labels = percent) +
  scale_colour_discrete(guide = guide_legend(reverse = TRUE)) +
  labs(y = "% 'yes' votes")
```


```{r}
by_country_year %>% 
  filter(country %in% c("United States", "Canada", "Mali", "Singapore", "Ghana", "Italy", 
                        "Spain", "Germany", "Israel")) %>% 
  mutate(country = fct_reorder(country, pc_yes)) %>% 
  ggplot(aes(x = year, y = pc_yes, colour = country)) +
  geom_line() +
  expand_limits(y = 0) +
  scale_y_continuous(labels = percent) +
  facet_wrap(~country) +
  theme(legend.position = "none") +
  labs(y = "% 'yes' votes")
```

```{r}

world_map <- map_data("world") %>% 
  as_tibble() %>% 
  regex_left_join(maps::iso3166 %>% 
                    select(mapname, country_code = a2),
                  c(region = "mapname")) %>% 
  filter(region != "Antarctica")

world_map %>% 
  left_join(by_country, by = "country_code") %>% 
  ggplot(aes(x = long, y = lat, group = group, fill = pc_yes)) +
  geom_polygon() +
  theme_map() +
  scale_fill_gradient2(low = "red", high = "blue", midpoint = 0.67, labels = percent) +
  labs(fill = "% of 'yes' votes")
  
```

```{r}
# this doesn't work if you want to do this comparison for a lot of countries

unvotes %>% 
  filter(country %in% c("United States", "Canada")) %>% 
  select(rcid, country, vote_number) %>% 
  pivot_wider(names_from = country, values_from = vote_number, values_fill = 0) %>% 
  rename(United_States = `United States`) %>% 
  summarise(correlation = cor(Canada, United_States))
```
```{r}
# widyr is such a good package
unvotes %>% 
  pairwise_cor(country, rcid, vote_number, sort = TRUE) %>% 
  filter(item1 == "United States")
```

```{r}
unvotes %>% 
  filter(country != "Zanzibar") %>% 
  pairwise_cor(country, rcid, vote_number, sort = TRUE) %>% 
  filter(item1 == "China") %>% # you can do this for any country
  slice(c(1:16, n()-0:15)) %>% 
  mutate(country = fct_reorder(item2, correlation)) %>% 
  ggplot(aes(correlation, country)) +
  geom_errorbarh(height = 0, aes(xmin = correlation, # creates lollipop graph with everything relative to 0
                                 xmax = 0)) +
  geom_point() +
  labs(x = "How much a country's voting record is correlated with the US")
```

```{r}
country_correlations <- unvotes %>% 
  filter(country != "Zanzibar") %>% 
  pairwise_cor(country, rcid, vote_number, sort = TRUE) %>% 
  mutate(continent1 = countrycode(item1, "country.name", "continent"),
         continent2 = countrycode(item2, "country.name", "continent"))

country_correlations %>% 
  group_by(item1) %>% 
  summarise(median_correlation = median(correlation),
            avg_correlation = mean(correlation)) %>% 
  arrange(desc(median_correlation))
```

```{r}
country_correlations %>% 
  filter(!is.na(continent1), !is.na(continent2)) %>% 
  group_by(continent1, continent2) %>% 
  summarise(avg_correlation = mean(correlation)) %>% 
  arrange(desc(avg_correlation))
```

```{r}
country_correlations %>% 
  filter(!is.na(continent1), !is.na(continent2)) %>%
  filter(continent1 == continent2) %>% 
  group_by(item1) %>% 
  summarise(avg_intracontinent_corr = mean(correlation)) %>% 
  arrange(desc(avg_intracontinent_corr))
```

```{r}
rc_words <- tt$roll_calls %>% 
  filter(!is.na(short)) %>% 
  unnest_tokens(word, short) %>% # "word" here just names the output column
  anti_join(stop_words, by = "word") %>%
  distinct(rcid, word) %>% 
  add_count(word, name = "word_count") %>% # adds a count column 
  filter(word_count >= 100) # limits the size of rc_words
```

```{r}
unvotes %>% 
  inner_join(rc_words, by = "rcid") %>% 
  filter(country %in% c("United Kingdom", "United States"))%>% # you can do this for any countries
  group_by(word, country) %>% 
  summarise_votes(min_votes = 100) %>% 
  mutate(word = fct_reorder(word, pc_yes,
                            function(x) max(x) - min(x))) %>% # function to sort by difference
  ggplot(aes(x = pc_yes, y = word)) +
  geom_point(aes(size = n_votes, colour = country)) +
  expand_limits(x= 0) +
  labs(x = "% 'yes' votes") +
  scale_x_continuous(labels = percent)
```
```{r}
by_country_word <- unvotes %>% 
  inner_join(rc_words, by = "rcid") %>% 
  group_by(word, country) %>% 
  summarise_votes(min_votes = 0)

# this produces the most popular issues overall, it doesn't really distinguish between countries
# ass the 1st dimension refers to word 
by_country_word %>% 
  widely_svd(word, country, pc_yes) %>% 
  filter(dimension == 1) %>% 
  mutate(word = reorder_within(word, value, dimension))%>% 
  top_n(20, abs(value)) %>% 
  ggplot(aes(x = value, y = word)) +
  geom_col() +
  scale_y_reordered()

# changing the dimension to the 2nd, we can see what drives the most variation in the dataset
# which is to say a country voting one way on "arms" would vote the other way on "africa"
by_country_word %>% 
  widely_svd(word, country, pc_yes) %>% 
  filter(dimension == 2) %>% 
  mutate(word = reorder_within(word, value, dimension))%>% 
  top_n(30, abs(value)) %>% 
  ggplot(aes(x = value, y = word)) +
  geom_col() +
  scale_y_reordered()
  
```


```{r}
unvotes %>% 
  distinct(issue2) %>% arrange(issue2)
```

```{r}
unvotes <- unvotes %>% 
  mutate(issue = str_to_upper(issue)) %>% 
  mutate(issue2 = case_when(str_detect(issue, "ADMISSION") ~ "ADMISSION",
                            str_detect(issue, "ANTARCTICA|ANTARCITCA") ~ "ANTARCTICA",
                            str_detect(issue, "WOMEN|WOMAN") ~ "WOMEN", 
                            str_detect(issue, "ALGERIA") ~ "ALGERIA", 
                            str_detect(issue, "ANGOLA") ~ "ANGOLA", 
                            str_detect(issue, "INTERNATIONAL LAW") ~ "INTERNATIONAL_LAW", 
                            str_detect(issue, "COMMODITIES") ~ "COMMODITIES",
                            str_detect(issue, "CARIBBEAN") ~ "CARIBBEAN", 
                            str_detect(issue, "CONFERENCE") ~ "CONFERENCES",
                            str_detect(issue, "CREDENTIAL") ~ "CREDENTIALS", 
                            str_detect(issue, "TRUSTEESHIP") ~ "TRUSTEESHIP",
                            str_detect(issue, "APARTHEID|ARAPTHEID") ~ "APARTHEID",
                            str_detect(issue, "NUCLEAR|FISSIONABLE") ~ "NUCLEAR",
                            str_detect(issue, "CHEMICAL|BIOLOGICAL") ~ "CHEMICAL_BIOLOGICAL_WEAPONS", 
                            str_detect(issue, "ARM|WEAPON|MISSILE") ~ "OTHER_ARMAMENTS",
                            str_detect(issue, "BUDGET") ~ "BUDGET",
                            str_detect(issue, "COLONI|DECOLOI") ~ "DECOLONISATION",
                            str_detect(issue, "CONGO") ~ "CONGO",
                            str_detect(issue, "DISASTER") ~ "DISASTER_RELIEF",
                            str_detect(issue, "ECONOMIC") ~ "ECONOMIC",
                            str_detect(issue, "ECOSOC") ~ "ECOSOC",
                            str_detect(issue, "ISRAEL") ~ "ISRAEL",
                            str_detect(issue, "HUNGARY") ~ "HUNGARY",
                            str_detect(issue, "KOSOVO") ~ "KOSOVO",
                            str_detect(issue, "MIDDLE EAST") ~ "MIDDLE_EAST",
                            str_detect(issue, "NAMIBIA") ~ "NAMIBIA",
                            str_detect(issue, "GOVERNING") ~ "NON_SELF_GOVERNING_TERRITORIES", 
                            str_detect(issue, "PALESTIN|PLO") ~ "PALESTINE",
                            str_detect(issue, "SOUTH AFRICA") ~ "SOUTH_AFRICA",
                            str_detect(issue, "SUEZ") ~ "SUEZ_CANAL",
                            str_detect(issue, "OUTER SPACE") ~ "OUTER_SPACE", 
                            str_detect(issue, "U.N.|UN |ACCOMODATION|UN-") ~ "UN_INTERNAL",
                            str_detect(issue, "UNCTAD") ~ "UNCTAD", 
                            str_detect(issue, "RACIAL|RACIS") ~ "RACISM", 
                            str_detect(issue, "INDEPENDENCE|DETERMINATION") ~ "INDEPENDENCE",
                            str_detect(issue, "MINES|REMNANTS") ~ "MINES",
                            str_detect(issue, "DEVELOPMENT") ~ "DEVELOPMENT", 
                            str_detect(issue, "AMEND") ~ "AMENDMENTS",
                            str_detect(issue, "HUMAN RIGHTS|RIGHT") ~ "HUMAN_RIGHTS",
                            str_detect(issue, "TRADE") ~ "TRADE",
                            str_detect(issue, "INDIAN OCEAN") ~ "INDIAN_OCEAN",
                            str_detect(issue, "GOLAN") ~ "GOLAN_HEIGHTS",
                            str_detect(issue, "SECURITY COUNCIL") ~ "SECURITY_COUNCIL", 
                            str_detect(issue, "TECHNOLOGY") ~ "TECHNOLOGY", 
                            str_detect(issue, "RWANDA-BURUNDI") ~ "RWANDA_BURUNDI", 
                            str_detect(issue, "REFUGE") ~ "REFUGEE",
                            str_detect(issue, "PEACEKEEPING") ~ "PEACEKEEPING",  
                            str_detect(issue, "PERSONNEL|PENSION|STAFF|RETIREMENT") ~ "PERSONNEL_PENSIONS", 
                            str_detect(issue, "LAW OF THE SEA") ~ "LAW_OF_THE_SEA",
                            str_detect(issue, "PROLIFERATION|TEST BAN|TEST-BAN") ~ "PROLIFERATION",
                            str_detect(issue, "MILITARY") ~ "MILITARY_OTHER", 
                            str_detect(issue, "LEBANON") ~ "LEBANON", 
                            str_detect(issue, "LAND-LOCKED|LAND LOCKED") ~ "LAND_LOCKED_COUNTRIES",
                            str_detect(issue, "LABOUR") ~ "LABOUR", 
                            str_detect(issue, "KOREA") ~ "KOREA",
                            str_detect(issue, "JERUSALEM") ~ "JERUSALEM",
                            str_detect(issue, "TERRORISM") ~ "TERRORISM", 
                            str_detect(issue, "ICJ") ~ "ICJ",
                            str_detect(issue, "IAEA|ATOMIC|URANIUM|RADIOACTIVE") ~ "NUCLEAR_POWER",
                            str_detect(issue, "GLOBALIZATION") ~ "GLOBALISATION",
                            str_detect(issue, "GENERAL ASSEMBLY") ~ "GENERAL_ASSEMBLY", 
                            str_detect(issue, "ENVIRONMENT|SUSTAINABLE") ~ "ENVIRONMENT",
                            str_detect(issue, "DEMOCRA") ~ "DEMOCRACY",
                            str_detect(issue, "CUBA") ~ "CUBA", 
                            str_detect(issue, "CHARTER") ~ "UN_CHARTER",
                            str_detect(issue, "CAPITAL PUNISMENT|EXECUTION") ~ "CAPITAL_PUNISHMENT",
                            str_detect(issue, "PEACE AND SECURITY|PEACE") ~ "PEACE_SECURITY",
                            str_detect(issue, "SEA BED") ~ "SEA_BED", 
                            str_detect(issue, "SOUTH WEST AFRICA") ~ "SOUTH_WEST_AFRICA", 
                            str_detect(issue, "SOUTHERN AFRICA") ~ "SOUTHERN_AFRICA", 
                            str_detect(issue, "U.S.") ~ "UNITED_STATES",
                            str_detect(issue, "WORKING LANGUAGE") ~ "WORKING_LANGUAGES",
                            TRUE ~ issue
                            ))
```

```{r}
unvotes %>% 
  group_by(issue2) %>% 
  summarise_votes() %>% 
  mutate(issue2 = fct_reorder(issue2, pc_yes)) %>% 
  filter(n_votes > 500,
         !is.na(issue2)) %>%
  tail(40) %>% 
  ggplot(aes(x = pc_yes, y = issue2)) + 
  geom_point(aes(size = n_votes)) +
  scale_x_continuous(labels = percent) +
  scale_size_continuous(range = c(0.5, 4)) +
  theme(axis.text.y = element_text(size = 4))
```

```{r}
unvotes %>% 
  filter(issue2 == "HUMAN_RIGHTS") %>% 
  group_by(country) %>% 
  summarise_votes() %>% 
  mutate(country = fct_reorder(country, pc_yes)) %>% 
  tail(30) %>% 
  ggplot(aes(x = pc_yes, y = country)) +
  geom_point(aes(size = n_votes)) +
  scale_x_continuous(labels = percent) +
  scale_size_continuous(range = c(0.5, 4)) +
  theme(axis.text.y = element_text(size = 5.5)) +
  labs(x = "% voted for human rights",
       y = "",
       title = "Countries which voted for human rights the least")
  
```
```{r}
unvotes %>% 
  filter(issue2 == "HUMAN_RIGHTS") %>% 
  select(issue) %>% distinct()
```

