---
title: "Untitled"
output: html_document
date: '2023-01-02'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rvest)
library(tidyverse)
library(xml2)

```

```{r}
url <-  "https://raw.githack.com/ccs-amsterdam/r-course-material/master/miscellaneous/simple_html.html"

# Hashes are important when filling in an ID name

read_html(url) %>% 
  html_element("#exampleTable") %>% 
  html_table()
  
read_html(url) %>% 
  html_element("#steve") %>% 
  html_table()
```

```{r}

# When you do html_element(), you get a single node, 
# However, when you use html_elements(), you get a nodeset
read_html(url) %>% 
  html_elements(".someTable") %>% 
  html_table()
```

```{r}
df <- 'https://reliefweb.int/updates?advanced-search=%28PC241%29_%28F10%29' %>%
  read_html() %>%
  html_elements('a') %>%
  html_attr("href") %>% 
  as_tibble() %>% 
  filter(str_detect(value, "https://"))

```

```{r}
site <-  read_html("https://reliefweb.int/report/ukraine/ukraine-emergency-unhcr-operational-response-delivery-updates-28-december-2022-enuk")

site_text <- html_text2(site) %>% 
  as_tibble()

 
source <- {str_match(site_text, 
                    "\nSource\n\\s*(.*?)\\s*\n") [, 2]} 

text <- {str_match(site_text, 
                    "(?s)Download Report\\s*(.*?)\\s*Report details") [, 2]} 

site_text %>% 
  mutate(source = )

```
```{r}
site2 <- read_html("https://reliefweb.int/report/ukraine/war-ukraine-situation-report-who-ukraine-country-office-issue-no38-30-december-2022") %>% html_text2()
```


