---
title: "Untitled"
output: html_document
---

### setup 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(broom)
library(tidytext)
library(widyr)
library(glmnet)
library(textdata)
library(scales)
theme_set(theme_light())

wine <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv") %>% 
  select(-1) %>% 
  extract(title, "year", "(20\\d\\d)", convert = TRUE, remove = FALSE) %>% 
  mutate(year = ifelse(year < 1900, NA, year)) %>% 
  filter(!is.na(price))
```

```{r}
glimpse(wine)

wine %>% count(country, sort = TRUE)

```

```{r}
wine %>% count(designation, sort = TRUE)

wine %>% count(country, region_1, sort = TRUE)

wine %>% count(taster_name, sort = TRUE)

wine %>% count(variety, sort = TRUE)
```

```{r}
wine %>% 
  filter(!is.na(designation)) %>% 
  count(variety, designation, sort = TRUE)
```
```{r}
wine %>% 
  ggplot(aes(year)) +
  geom_histogram()


```

```{r}
wine %>% ggplot(aes(points)) +
  geom_histogram(binwidth = 1)

wine %>% 
  ggplot(aes(price)) +
  geom_histogram() +
  scale_x_log10()
  
  
```

```{r}
wine %>% 
  ggplot(aes(x = price, y = points)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm") +
  scale_x_log10()

```
### Model

```{r}
model <- wine %>%
  replace_na(list(taster_name = "Missing", country = "Missing")) %>% 
  mutate(country     = fct_relevel(fct_lump(country, 7), "US"),
         taster_name = fct_relevel(fct_lump(taster_name, 6), "Missing")) %>% 
  lm(points ~ log2(price) + country + year + taster_name, data = .)


model %>% 
  tidy(conf.int = TRUE) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = str_replace(term, "country", "Country: "),
         term = str_replace(term, "taster_name", "Taster: "),
         term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(x = estimate, y = term)) +
  geom_point() + 
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0)
  

```

```{r}
tidy(anova(model)) %>% 
  mutate(sumsq / sum(sumsq))
```

### Lasso Regression

```{r}
wine_words <- wine %>% 
  mutate(wine_id = row_number()) %>% 
  unnest_tokens(word, description) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(!word %in% c("wine", "drink"))

wine_words %>% 
  count(word, sort = TRUE) %>% 
  head(20) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  ggplot(aes(x = word, y = n)) + 
  geom_col() +
  coord_flip()
```

```{r}
words_filtered <- wine_words %>% 
  distinct(wine_id, word) %>% 
  add_count(word) %>% 
  filter(n >= 100, str_detect(word, "[a-z]"))

words_filtered %>% 
  pairwise_cor(word, wine_id, sort = TRUE)
```

```{r}
words_matrix <- words_filtered %>% 
  cast_sparse(wine_id, word)

wine_ids <- as.integer(rownames(words_matrix))
scores <- wine$points[wine_ids]

glmnet_model <- glmnet(words_matrix, scores)

glmnet_model %>% 
  tidy() %>% 
  arrange(step) %>% 
  filter(term %in% c("rich", "black", "simple", "complex", "vineyard")) %>% 
  ggplot(aes(x = lambda, y = estimate, colour = term)) +
  geom_line() +
  scale_x_log10() +
  geom_hline(lty = 2, yintercept = 0)

# how do we pick a lambda? we use cross-validated glmnet

glmnet_model %>% 
  tidy() %>% 
  count(lambda) %>% 
  ggplot(aes(x = lambda, y = n)) +
  geom_line() +
  scale_x_log10()

words_matrix_extra <- cbind(words_matrix, log_price = log2(wine$price[wine_ids]))

cv_glmnet_model <- cv.glmnet(words_matrix_extra, scores)

plot(cv_glmnet_model)



```

```{r}
lexicon <- cv_glmnet_model$glmnet.fit %>% 
  tidy() %>% 
  filter(lambda == cv_glmnet_model$lambda.1se,
         term != "(Intercept)",
         term != "log_price") %>% 
  select(word = term, coefficient = estimate)

lexicon %>% 
  arrange(coefficient) %>% 
  group_by(direction = ifelse(coefficient < 0, "Negative", "Positive")) %>% 
  top_n(20, abs(coefficient)) %>% 
  ungroup() %>% 
  mutate(word = fct_reorder(word, coefficient)) %>% 
  ggplot(aes(x = word, y = coefficient, fill = direction)) +
  geom_col() + 
  coord_flip() +
  labs(x = "",
       y = "Estimated effect of words on wine points",
       title = "What words are predictive of a wine's score")

get_sentiments("bing")
```

```{r}
wine %>% 
  mutate(wine_id = row_number()) %>% 
  arrange(points) %>% 
  head(1) %>% 
  select(wine_id, description) %>% 
  pull(description)
```

### sentiments

```{r}
wine_words %>% 
  filter(wine_id %in% sample(unique(wine_id), 4)) %>% 
  distinct(word, title, points) %>% 
  mutate(wine = paste0(str_trunc(title, 30), "(", points, ")")) %>% 
  inner_join(lexicon, by = "word") %>% 
  mutate(word = fct_reorder(word, coefficient)) %>% 
  ggplot(aes(x = word, y = coefficient, fill = coefficient > 0)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  facet_wrap(~ wine, scales = "free_y") +
  labs(title = "How a lasso regression would predict each wine's score",
       subtitle = "Price was used as an extra term",
       x = "", 
       y = "Effect on score")
```


```{r}
wine %>%
  mutate(country = fct_relevel(fct_lump(country, 7), "US")) %>%
  ggplot(aes(x = country, y = points)) +
  geom_boxplot() +
  coord_flip()


```




